[package]
name = "sol-pessg"
version = "0.1.0"
authors = ["wan-nyan-wan <distributed.system.love@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-core = "1.6.6"
solana-sdk = "1.6.6"
rand = "0.8.3"